### ISSUE TITLE
Create "Measure" FS studio that can take all measurements needed

### ISSUE THREAD

**Issue by ethan92429** [AguaClara/onshapepy#14]
This issue is for further collaboration on the [Measure FeatureScript Studio](https://cad.onshape.com/documents/379f3f7b8ae77b02b702a487/w/0ad420b3718d5a2b6f6d712f/e/2e4fe1496c0fa6c042b89a73). The goal is to develop a feature that can take complex measurements depending on the entities being selected, much like the way the "measurement tool" on the lower right of the UI dynamically reports relevant measurements. [To see the discussion that spawned this, go here.](https://forum.onshape.com/discussion/comment/44081#Comment_44081)

Next step: merge "Measure Distance" and "Measure Area" into one "Measure" function that dynamically decides whether to measure distance or area based on the selected elements.

**Comment by ethan92429** [comment]
So far we store all the measurements into a "measurements" context variable.

**Comment by morganb21** [comment]
@ethan92429 
Would this be a suitable featurescript to use?
https://cad.onshape.com/documents/e048d057f445affb6a3af03a

**Comment by ethan92429** [comment]
Hi @morganb21! I can't seem to access the document you linked... [This](https://cad.onshape.com/documents/379f3f7b8ae77b02b702a487/w/0ad420b3718d5a2b6f6d712f/e/2e4fe1496c0fa6c042b89a73) is one that I've worked on and now works with onshapepy. It could use improvements, but it works alright for now.

**Comment by ethan92429** [comment]
Actually, I think the one I linked is good enough to close this!

**Comment by morganb21** [comment]
@ethan92429 
Sorry, i forgot to make it public :smile:
It should work now.
It has length, angle, distance, diameter, radius, and it is in the format of the default variable feature

**Comment by ethan92429** [comment]
@morganb21 this is great! Thanks! We'll definitely use this one.

**Comment by morganb21** [comment]
@ethan92429 
It can put this into a variable called #m that is a `map`
