### ISSUE TITLE
Link to the OnShape AguaClara repo where the drawing is happening

### ISSUE THREAD

**Issue by monroews** [AguaClara/onshapepy#6]
perhaps put a link on the wiki for this repo?

**Comment by ethan92429** [comment]
We will be using an organization to store our documents. I will be setting up the org when I go in to meet with OnShape. For now, we have several documents. [Here is the one with the current plants imported. ](https://cad.onshape.com/documents/5a7585ae3248902548b02541/w/349594d2eb30a283f019807e/e/0ab9b7d2f03c8fff5b16e007) [Here is our standard pipe library](https://cad.onshape.com/documents/de0b979bd2526029daafe060/w/8043876c6f38336511d43098/e/7a6d9c6a8583cdf983aee11e). When we have one org this will be simpler.

**Comment by ethan92429** [comment]
You can now see the "AguaClara files" by looking at the team page.

![screen shot 2018-09-13 at 22 44 30](https://user-images.githubusercontent.com/8585379/45526788-9eb64680-b7a6-11e8-8cb7-78217d45d992.png)
